<?php


namespace Module\NullosAdmin\Api\GeneratedObject;


use XiaoApi\Object\TableCrudObject;

/**
 * This file was generated by the DbObjectGenerator.
 * You should not edit it manually, otherwise you
 * might loose your edits on the next update.
 *
 * You are supposed to extend this object.
 */
class GeneratedUser extends TableCrudObject
{

    public function __construct()
    {
        parent::__construct();
        $this->table = "nul_user";
        $this->primaryKey = ['id'];
    }


    //--------------------------------------------
    //
    //--------------------------------------------
    protected function getCreateData(array $data)
    {
        $base = [
			'id' => null,
			'email' => '',
			'pass' => '',
			'avatar' => '',
			'pseudo' => '',
			'active' => 0,
			'date_created' => '',
			'date_last_connexion' => null,
		];
        $ret = array_replace($base, array_intersect_key($data, $base));

        if ("" === $ret["date_last_connexion"]) {
            $ret["date_last_connexion"] = null;
        }


        return $ret;
    }


}