-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 11:45:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kamille
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kamille
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kamille` DEFAULT CHARACTER SET utf8 ;
USE `kamille` ;

-- -----------------------------------------------------
-- Table `kamille`.`nul_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`nul_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `pass` VARCHAR(64) NOT NULL,
  `avatar` VARCHAR(256) NOT NULL,
  `pseudo` VARCHAR(64) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `date_created` DATETIME NOT NULL,
  `date_last_connexion` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`nul_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`nul_badge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kamille`.`nul_user_has_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kamille`.`nul_user_has_badge` (
  `user_id` INT NOT NULL,
  `badge_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `badge_id`),
  INDEX `fk_nul_user_has_nul_badge_nul_badge1_idx` (`badge_id` ASC),
  INDEX `fk_nul_user_has_nul_badge_nul_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_nul_user_has_nul_badge_nul_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `kamille`.`nul_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_nul_user_has_nul_badge_nul_badge1`
    FOREIGN KEY (`badge_id`)
    REFERENCES `kamille`.`nul_badge` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
